name: ndm
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.51.1=hf5d6505_1
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=hc20f281_2_cpython
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h2c6b04d_3
  - tzdata=2025c=h8577fbf_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - colorama==0.4.6
      - tqdm==4.67.1
prefix: C:\Users\ADMIN\.conda\envs\ndm
